version: '3.8'

services:
  tree_with_nodes_postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
      PGUSER: user
    network_mode: "host"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d my_database -U user"]
      interval: 1s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2g
        reservations:
          cpus: '1'
          memory: 1g

volumes:
  postgres_data:
